name: Functional Tests

on:
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project
        id: build-project
        run: mvn clean install -DskipTests -DskipReports

  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    needs: [ install ]
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Execute Cucumber Dry Run
        id: dry-run
        run: mvn verify -Dit.test=DryRunRunnerIT -DskipReports

  chrome-tests:
    name: Chrome Sanity Check
    runs-on: ubuntu-latest
    needs: [ install, dry-run ]
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - name: Run Chrome Tests
        id: run-chrome-tests
        run: mvn clean verify -Dtags='(@sanity) and (not @bug and not @skip)' -DparallelCount=3 -Denv=github -Dbrowser=chrome -Dheadless -Dremote=false
      - name: Upload Allure Results
        id: upload-allure-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-allure-results
          path: target/cucumber/allure-results/
          if-no-files-found: ignore
          retention-days: 1

  firefox-tests:
    name: Firefox Sanity Check
    runs-on: ubuntu-latest
    needs: [ install, dry-run ]
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      - name: Run Firefox Tests
        id: run-firefox-tests
        run: mvn clean verify -Dtags='(@sanity) and (not @bug and not @skip)' -DparallelCount=3 -Denv=github -Dbrowser=firefox -Dheadless -Dremote=false
      - name: Upload Allure Results
        id: upload-allure-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: firefox-allure-results
          path: target/cucumber/allure-results/
          if-no-files-found: ignore
          retention-days: 1

  report:
    name: Report
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ chrome-tests, firefox-tests ]
    timeout-minutes: 30
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
      - name: Generate Allure Report
        id: generate-allure-report
        run: |
          curl -LJO https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.zip
          unzip allure-2.26.0.zip
          ./allure-2.26.0/bin/allure generate chrome-allure-results -o chrome-allure-report --clean
          ./allure-2.26.0/bin/allure generate firefox-allure-results -o firefox-allure-report --clean
      - name: Move to Reports folder
        id: move-to-reports-folder
        run: |
          mv chrome-allure-results reports/chrome-allure-results
          mv firefox-allure-results reports/firefox-allure-results
        shell: bash
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete Unnecessary Artifacts
        id: delete-unnecessary-artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            chrome-allure-results
            firefox-allure-results
          failOnError: false
