name: Functional Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project
        id: build-project
        run: mvn clean install -DskipTests -DskipReports

  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    needs: [ install ]
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Execute Cucumber Dry Run
        id: dry-run
        run: mvn verify -Dit.test=DryRunRunnerIT -DskipReports

  chrome-tests:
    name: Chrome Sanity Check
    runs-on: ubuntu-latest
    needs: [ install, dry-run ]
    timeout-minutes: 30
    services:
      rbp-booking:
        image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
        ports:
          - 3000:3000
      rbp-room:
        image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
        ports:
          - 3001:3001
      rbp-branding:
        image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
        ports:
          - 3002:3002
      rbp-assets:
        image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
        ports:
          - 3003:3003
      rbp-auth:
        image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
        ports:
          - 3004:3004
      rbp-report:
        image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
        ports:
          - 3005:3005
      rbp-message:
        image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
        ports:
          - 3006:3006
      rbp-proxy:
        image: mwinteringham/restfulbookerplatform_proxy:latest
        ports:
          - 80:80
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - name: Run Chrome Tests
        id: run-chrome-tests
        run: mvn clean verify -Dtags='(not @bug and not @skip)' -DparallelCount=3 -Denv=github -Dbrowser=chrome -Dheadless -Dremote=false
      - name: Upload Allure Results
        id: upload-allure-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-allure-results
          path: target/cucumber/allure-results/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Cluecumber Report
        id: upload-cluecumber-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-cluecumber-report
          path: target/cucumber/cluecumber-report/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Cucumber HTML Report
        id: upload-cucumber-html-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-cucumber-html-report
          path: target/cucumber/cucumber-html-reports/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Chrome Tests Logs
        id: upload-test-logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chrome-tests-logs
          path: logs/
          if-no-files-found: ignore
          retention-days: 1

  firefox-tests:
    name: Firefox Sanity Check
    runs-on: ubuntu-latest
    needs: [ install, dry-run ]
    timeout-minutes: 30
    services:
      rbp-booking:
        image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
        ports:
          - 3000:3000
      rbp-room:
        image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
        ports:
          - 3001:3001
      rbp-branding:
        image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
        ports:
          - 3002:3002
      rbp-assets:
        image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
        ports:
          - 3003:3003
      rbp-auth:
        image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
        ports:
          - 3004:3004
      rbp-report:
        image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
        ports:
          - 3005:3005
      rbp-message:
        image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
        ports:
          - 3006:3006
      rbp-proxy:
        image: mwinteringham/restfulbookerplatform_proxy:latest
        ports:
          - 80:80
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      - name: Run Firefox Tests
        id: run-firefox-tests
        run: mvn clean verify -Dtags='(not @bug and not @skip)' -DparallelCount=3 -Denv=local -Dbrowser=firefox -Dheadless -Dremote=false
      - name: Upload Allure Results
        id: upload-allure-results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: firefox-allure-results
          path: target/cucumber/allure-results/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Cluecumber Report
        id: upload-cluecumber-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: firefox-cluecumber-report
          path: target/cucumber/cluecumber-report/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Cucumber HTML Report
        id: upload-cucumber-html-report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: firefox-cucumber-html-report
          path: target/cucumber/cucumber-html-reports/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Firefox Tests Logs
        id: upload-test-logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: firefox-tests-logs
          path: logs/
          if-no-files-found: ignore
          retention-days: 1

  report:
    name: Report
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ chrome-tests, firefox-tests ]
    timeout-minutes: 30
    permissions:
      actions: write
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
      - name: Fetch Chrome Allure History
        id: chrome-allure-history
        run: |
          curl --create-dirs -o ./chrome-allure-results/history/categories-trend.json https://levinine.github.io/functional-tests/chrome-allure-report/history/categories-trend.json
          curl --create-dirs -o ./chrome-allure-results/history/duration-trend.json https://levinine.github.io/functional-tests/chrome-allure-report/history/duration-trend.json
          curl --create-dirs -o ./chrome-allure-results/history/history-trend.json https://levinine.github.io/functional-tests/chrome-allure-report/history/history-trend.json
          curl --create-dirs -o ./chrome-allure-results/history/history.json https://levinine.github.io/functional-tests/chrome-allure-report/history/history.json
          curl --create-dirs -o ./chrome-allure-results/history/retry-trend.json https://levinine.github.io/functional-tests/chrome-allure-report/history/retry-trend.json
      - name: Fetch Firefox Allure History
        id: chrome-firefox-history
        run: |
          curl --create-dirs -o ./firefox-allure-results/history/categories-trend.json https://levinine.github.io/functional-tests/firefox-allure-report/history/categories-trend.json
          curl --create-dirs -o ./firefox-allure-results/history/duration-trend.json https://levinine.github.io/functional-tests/firefox-allure-report/history/duration-trend.json
          curl --create-dirs -o ./firefox-allure-results/history/history-trend.json https://levinine.github.io/functional-tests/firefox-allure-report/history/history-trend.json
          curl --create-dirs -o ./firefox-allure-results/history/history.json https://levinine.github.io/functional-tests/firefox-allure-report/history/history.json
          curl --create-dirs -o ./firefox-allure-results/history/retry-trend.json https://levinine.github.io/functional-tests/firefox-allure-report/history/retry-trend.json
      - name: Generate Allure Report
        id: generate-allure-report
        run: |
          curl -LJO https://github.com/allure-framework/allure2/releases/download/2.26.0/allure-2.26.0.zip
          unzip allure-2.26.0.zip
          ./allure-2.26.0/bin/allure generate chrome-allure-results -o chrome-allure-report --clean
          ./allure-2.26.0/bin/allure generate firefox-allure-results -o firefox-allure-report --clean
      - name: Move to Reports folder
        id: move-to-reports-folder
        run: |
          mv chrome-allure-report reports/chrome-allure-report
          mv chrome-cluecumber-report reports/chrome-cluecumber-report
          mv chrome-cucumber-html-report reports/chrome-cucumber-html-report
          mv firefox-allure-report reports/firefox-allure-report
          mv firefox-cluecumber-report reports/firefox-cluecumber-report
          mv firefox-cucumber-html-report reports/firefox-cucumber-html-report
        shell: bash
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v4
      - name: Upload Pages Artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete Unnecessary Artifacts
        id: delete-unnecessary-artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            *-allure-results
            *-cluecumber-report
            *-cucumber-html-report
          failOnError: false